name: Build
on: [ push ]
env:
  DOCKER_VERSION_FULL: "2.0.20"
  DOCKER_VERSION_MINOR: "2.0"
  DOCKER_VERSION_MAJOR: "2"
jobs:

  images:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Build and push keepalived
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          push: true
          tags: |
            thibaultmorin/keepalived:${{ env.DOCKER_VERSION_MAJOR }}
            thibaultmorin/keepalived:${{ env.DOCKER_VERSION_MINOR }}
            thibaultmorin/keepalived:${{ env.DOCKER_VERSION_FULL }}
          build-args: |
            version=${{ env.DOCKER_VERSION_FULL }}
            git_sha=${{ github.sha }}
